# Generated by Django 4.2.23 on 2025-07-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad_por_presentacion_base',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='presentacion_base',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad del Movimiento (en unidad de venta)'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='referencia_doc',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia de Documento'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='stock_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.stockproducto', verbose_name='Stock de Producto Afectado'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo')], max_length=50, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='aplica_receta',
            field=models.BooleanField(default=False, verbose_name='Requiere Receta Médica'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='es_controlado',
            field=models.BooleanField(default=False, verbose_name='Es Producto Controlado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra_promedio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Costo promedio de la unidad de VENTA MÍNIMA.', max_digits=10, verbose_name='Precio de Compra Promedio'),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='cantidad',
            field=models.IntegerField(default=0, help_text="Cantidad del producto en su 'unidad de venta mínima' (ej. número de tabletas).", verbose_name='Cantidad Disponible'),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubicación en Almacén'),
        ),
        migrations.CreateModel(
            name='UnidadPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Unidad')),
                ('factor_conversion', models.PositiveIntegerField(default=1, help_text="Ej: Si esta unidad es 'Blister' y el padre es 'Caja', y hay 10 blisters en una caja, el factor es 10.", verbose_name='Cantidad Contenida en el Padre')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos', to='inventario.unidadpresentacion', verbose_name='Unidad Contenedora (Padre)')),
            ],
            options={
                'verbose_name': 'Unidad de Presentación',
                'verbose_name_plural': 'Unidades de Presentación',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_compra',
            field=models.ForeignKey(blank=True, help_text='La unidad en la que normalmente se compra este producto (ej. Caja).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_comprados', to='inventario.unidadpresentacion', verbose_name='Unidad de Compra Principal'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, help_text='La unidad mínima en la que se vende el producto (ej. Tableta, Unidad).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_vendidos', to='inventario.unidadpresentacion', verbose_name='Unidad de Venta Mínima'),
        ),
    ]
