# Generated by Django 4.2.23 on 2025-07-03 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_producto_cantidad_por_presentacion_base_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código de Barras (EAN)'),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='cantidad',
            field=models.PositiveIntegerField(default=0, help_text="Cantidad del producto en su 'unidad de venta mínima' (ej. número de tabletas).", verbose_name='Cantidad Disponible'),
        ),
    ]
