# Generated by Django 4.2.23 on 2025-07-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_producto_codigo_barras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta (Caja/Presentación Principal)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_blister',
            field=models.PositiveIntegerField(default=1, help_text='Número de unidades básicas que contiene un blíster.', verbose_name='Unidades por Blíster'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidades_por_caja',
            field=models.PositiveIntegerField(default=1, help_text='Total de unidades básicas (pastillas, cápsulas) que contiene la caja.', verbose_name='Unidades por Caja'),
        ),
    ]
