# Generated by Django 4.2.23 on 2025-07-20 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_producto_precio_venta_producto_unidades_por_blister_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra_promedio',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta_sugerido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta Sugerido (Global)'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Compra del Lote'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta en esta Sucursal'),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventario.producto', verbose_name='Producto'),
        ),
    ]
