# Generated by Django 4.2.23 on 2026-06-11 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_remove_producto_precio_compra_promedio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precio_incluye_igv',
            field=models.BooleanField(default=True, verbose_name='Precio Incluye IGV'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_igv',
            field=models.CharField(choices=[('10', 'Gravado - Operación Onerosa'), ('20', 'Exonerado'), ('30', 'Inafecto')], default='10', max_length=2, verbose_name='Tipo de Afectación IGV'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='margen_ganancia_sugerido',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Margen de Ganancia Sugerido (%)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta_sugerido',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta Sugerido'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_comprados', to='inventario.unidadpresentacion', verbose_name='Unidad de Compra Principal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos_vendidos', to='inventario.unidadpresentacion', verbose_name='Unidad de Venta Mínima'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades_por_blister',
            field=models.PositiveIntegerField(default=1, verbose_name='Unidades por Blíster'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidades_por_caja',
            field=models.PositiveIntegerField(default=1, verbose_name='Unidades por Caja'),
        ),
    ]
