# Generated by Django 4.2.23 on 2026-06-19 02:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sucursal_es_principal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventario', '0006_producto_precio_incluye_igv_producto_tipo_igv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioProductoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de Venta')),
                ('precio_minimo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mínimo Permitido')),
                ('precio_mayorista', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio Mayorista')),
                ('usa_precio_matriz', models.BooleanField(default=True, verbose_name='Usa precio de matriz')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Precio por Sucursal',
                'verbose_name_plural': 'Precios por Sucursal',
                'ordering': ['sucursal__nombre', 'producto__nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='stockproducto',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='stockproducto',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='cantidad_anterior',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Antes del Movimiento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='cantidad_nueva',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Después del Movimiento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='core.sucursal', verbose_name='Sucursal Destino'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='sucursal_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_origen', to='core.sucursal', verbose_name='Sucursal Origen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Producto Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU Interno'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='cantidad_disponible',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible'),
        ),
        migrations.AddField(
            model_name='stockproducto',
            name='cantidad_reservada',
            field=models.PositiveIntegerField(default=0, verbose_name='Cantidad Reservada'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.IntegerField(verbose_name='Cantidad del Movimiento en Unidad Mínima'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='stock_afectado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.stockproducto', verbose_name='Stock de Producto Afectado'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to='core.sucursal', verbose_name='Sucursal del Movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('VENTA', 'Venta'), ('ANULACION_VENTA', 'Anulación de Venta'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('TRASLADO_SALIDA', 'Traslado - Salida'), ('TRASLADO_ENTRADA', 'Traslado - Entrada')], max_length=50, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que realizó el movimiento'),
        ),
        migrations.AlterField(
            model_name='stockproducto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_productos', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'sucursal'], name='inventario__product_4aa29e_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['tipo_movimiento'], name='inventario__tipo_mo_89d562_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha_movimiento'], name='inventario__fecha_m_ff429d_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['referencia_doc'], name='inventario__referen_8fac5b_idx'),
        ),
        migrations.AddField(
            model_name='precioproductosucursal',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_sucursal', to='inventario.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='precioproductosucursal',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_productos', to='core.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterUniqueTogether(
            name='precioproductosucursal',
            unique_together={('producto', 'sucursal')},
        ),
    ]
