# Generated by Django 4.2.23 on 2025-07-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmacia',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
