# Generated by Django 4.2.23 on 2026-05-05 03:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_farmacia_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionfacturacionelectronica',
            name='certificado_pem',
            field=models.TextField(blank=True, verbose_name='Contenido del Certificado .PEM'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturacionelectronica',
            name='clave_certificado',
            field=models.CharField(blank=True, max_length=255, verbose_name='Clave del Certificado'),
        ),
        migrations.AlterField(
            model_name='configuracionfacturacionelectronica',
            name='modo_produccion',
            field=models.BooleanField(default=False, verbose_name='Modo Producción Activo'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='configuracion_facturacion_electronica',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.configuracionfacturacionelectronica', verbose_name='Configuración FE Asociada'),
        ),
        migrations.AlterField(
            model_name='farmacia',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos_farmacias/', verbose_name='Logo de la Farmacia'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='administrador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador de Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='codigo',
            field=models.CharField(max_length=10, unique=True, verbose_name='Código de Sucursal'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='farmacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='core.farmacia', verbose_name='Farmacia a la que pertenece'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='farmacia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.farmacia', verbose_name='Farmacia Asociada'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.rol', verbose_name='Rol del Usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal', verbose_name='Sucursal Asociada'),
        ),
        migrations.CreateModel(
            name='SerieComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura Electrónica'), ('03', 'Boleta de Venta Electrónica')], max_length=2, verbose_name='Tipo de Comprobante')),
                ('serie', models.CharField(max_length=4, verbose_name='Serie')),
                ('correlativo_actual', models.PositiveIntegerField(default=0, verbose_name='Último correlativo usado')),
                ('ambiente', models.CharField(choices=[('BETA', 'Beta / Pruebas'), ('PRODUCCION', 'Producción')], default='BETA', max_length=20, verbose_name='Ambiente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('farmacia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_comprobantes', to='core.farmacia', verbose_name='Farmacia')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_comprobantes', to='core.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Serie de Comprobante',
                'verbose_name_plural': 'Series de Comprobantes',
                'ordering': ['farmacia', 'sucursal', 'tipo_comprobante', 'serie'],
                'unique_together': {('farmacia', 'sucursal', 'tipo_comprobante', 'serie', 'ambiente')},
            },
        ),
    ]
