# Generated by Django 4.2.23 on 2026-06-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_configuracionfacturacionelectronica_certificado_pem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='es_principal',
            field=models.BooleanField(default=False),
        ),
    ]
