# Generated by Django 4.2.23 on 2025-06-17 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventario", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransferenciaStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.IntegerField(
                        help_text="Cantidad del producto en su 'presentación base' a transferir.",
                        verbose_name="Cantidad a Transferir",
                    ),
                ),
                (
                    "fecha_solicitud",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Solicitud"
                    ),
                ),
                (
                    "fecha_envio",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Envío"
                    ),
                ),
                (
                    "fecha_recepcion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Recepción"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Envío"),
                            ("ENVIADO", "Enviado"),
                            ("RECIBIDO", "Recibido"),
                            ("RECHAZADO", "Rechazado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Transferencia",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "enviado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="envios_transferencia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado Por",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                        verbose_name="Producto a Transferir",
                    ),
                ),
                (
                    "recibido_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recepciones_transferencia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recibido Por",
                    ),
                ),
                (
                    "solicitado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_transferencia",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Solicitado Por",
                    ),
                ),
                (
                    "sucursal_destino",
                    models.ForeignKey(
                        help_text="Sucursal a la que se destina el producto.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_recibidas",
                        to="core.sucursal",
                        verbose_name="Sucursal de Destino",
                    ),
                ),
                (
                    "sucursal_origen",
                    models.ForeignKey(
                        help_text="Sucursal desde la que se envía el producto.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transferencias_enviadas",
                        to="core.sucursal",
                        verbose_name="Sucursal de Origen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transferencia de Stock",
                "verbose_name_plural": "Transferencias de Stock",
                "ordering": ["-fecha_solicitud"],
            },
        ),
    ]
