# Generated by Django 4.2.23 on 2026-06-19 03:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_sucursal_es_principal'),
        ('inventario', '0007_precioproductosucursal_remove_stockproducto_cantidad_and_more'),
        ('traslados', '0002_detalletransferencia_transferencia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleTrasladoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50, verbose_name='Lote')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad a Trasladar')),
                ('cantidad_recibida', models.PositiveIntegerField(default=0, verbose_name='Cantidad Recibida')),
                ('observaciones', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto', verbose_name='Producto')),
                ('stock_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_traslado_origen', to='inventario.stockproducto', verbose_name='Stock Origen')),
            ],
            options={
                'verbose_name': 'Detalle de Traslado',
                'verbose_name_plural': 'Detalles de Traslado',
            },
        ),
        migrations.CreateModel(
            name='TrasladoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('RECIBIDO', 'Recibido'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_entrantes', to='core.sucursal', verbose_name='Sucursal Destino')),
                ('sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_salientes', to='core.sucursal', verbose_name='Sucursal Origen')),
                ('usuario_envia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Envía')),
                ('usuario_recibe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='traslados_recibidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Recibe')),
                ('usuario_solicita', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_solicitados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Solicita')),
            ],
            options={
                'verbose_name': 'Traslado de Stock',
                'verbose_name_plural': 'Traslados de Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='enviado_por',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='recibido_por',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='solicitado_por',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='sucursal_destino',
        ),
        migrations.RemoveField(
            model_name='transferencia',
            name='sucursal_origen',
        ),
        migrations.DeleteModel(
            name='DetalleTransferencia',
        ),
        migrations.DeleteModel(
            name='Transferencia',
        ),
        migrations.AddField(
            model_name='detalletrasladostock',
            name='traslado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='traslados.trasladostock', verbose_name='Traslado'),
        ),
    ]
