# Generated by Django 4.2.23 on 2025-06-17 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
        ("inventario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_venta",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha y Hora de Venta"
                    ),
                ),
                (
                    "tipo_comprobante",
                    models.CharField(
                        choices=[
                            ("TICKET", "Ticket de Venta"),
                            ("BOLETA", "Boleta de Venta"),
                            ("FACTURA", "Factura Electrónica"),
                            ("RECIBO", "Recibo Simple"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Comprobante",
                    ),
                ),
                (
                    "numero_comprobante",
                    models.CharField(
                        blank=True,
                        help_text="Número único del documento de venta (ej. serie-correlativo).",
                        max_length=50,
                        null=True,
                        unique=True,
                        verbose_name="Número de Comprobante",
                    ),
                ),
                (
                    "metodo_pago",
                    models.CharField(
                        choices=[
                            ("EFECTIVO", "Efectivo"),
                            ("TARJETA_CREDITO", "Tarjeta de Crédito"),
                            ("TARJETA_DEBITO", "Tarjeta de Débito"),
                            ("YAPE", "Yape"),
                            ("PLIN", "Plin"),
                            ("CRIPTOMONEDA", "Criptomoneda"),
                            ("TRANSFERENCIA_BANCARIA", "Transferencia Bancaria"),
                            ("CREDITO_CLIENTE", "Crédito (Cuenta Corriente Cliente)"),
                            ("OTRO", "Otro Método"),
                        ],
                        max_length=50,
                        verbose_name="Método de Pago Principal",
                    ),
                ),
                (
                    "total_venta",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total de la Venta",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Subtotal (Sin Impuestos)",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Impuestos (IGV/IVA)",
                    ),
                ),
                (
                    "descuento_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Descuento Total Aplicado a la Venta",
                    ),
                ),
                (
                    "estado_facturacion_electronica",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Envío FE"),
                            ("ENVIADO", "Enviado FE"),
                            ("ACEPTADO", "Aceptado por SUNAT/AFIP/etc."),
                            ("RECHAZADO", "Rechazado por SUNAT/AFIP/etc."),
                            ("ANULADO", "Comprobante Anulado FE"),
                            ("N/A", "No Aplica FE"),
                        ],
                        default="N/A",
                        max_length=20,
                        verbose_name="Estado Facturación Electrónica",
                    ),
                ),
                (
                    "uuid_comprobante_fe",
                    models.CharField(
                        blank=True,
                        help_text="Identificador único del comprobante electrónico (si aplica).",
                        max_length=100,
                        null=True,
                        verbose_name="UUID Comprobante FE",
                    ),
                ),
                (
                    "cliente",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cliente al que se realizó la venta (opcional si es venta genérica).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clientes.cliente",
                        verbose_name="Cliente Asociado",
                    ),
                ),
                (
                    "sucursal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.sucursal",
                        verbose_name="Sucursal de Venta",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Venta",
                "verbose_name_plural": "Ventas",
                "ordering": ["-fecha_venta"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVenta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad vendida en la 'Unidad de Venta' especificada.",
                        max_digits=10,
                        verbose_name="Cantidad Vendida",
                    ),
                ),
                (
                    "unidad_venta",
                    models.CharField(
                        choices=[
                            ("CAJA", "Caja"),
                            ("BLISTER", "Blíster"),
                            ("UNIDAD", "Unidad (Pastilla/Cápsula)"),
                            ("FRASCO", "Frasco"),
                            ("TUBO", "Tubo"),
                            ("GRAMO", "Gramo"),
                            ("MILILITRO", "Mililitro"),
                        ],
                        help_text="Unidad en la que se vendió el producto (ej. 'CAJA', 'BLISTER', 'UNIDAD').",
                        max_length=20,
                        verbose_name="Unidad de Venta",
                    ),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio Unitario (por la unidad de venta)",
                    ),
                ),
                (
                    "subtotal_linea",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Subtotal de la Línea (sin descuento ni impuestos)",
                    ),
                ),
                (
                    "descuento_linea",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Descuento por Línea",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                        verbose_name="Producto Vendido",
                    ),
                ),
                (
                    "stock_producto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Referencia al lote de stock específico del cual se realizó la venta (para trazabilidad).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario.stockproducto",
                        verbose_name="Lote de Stock Afectado",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="ventas.venta",
                        verbose_name="Venta Asociada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Venta",
                "verbose_name_plural": "Detalles de Ventas",
            },
        ),
    ]
