# Generated by Django 4.2.23 on 2025-07-10 06:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0003_alter_producto_codigo_barras_and_more'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='descuento_linea',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='descuento_total',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='monto_descuento_linea',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto de Descuento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la Venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Monto Total del Descuento'),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_recibido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Recibido (Efectivo)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='observaciones_fe',
            field=models.TextField(blank=True, help_text='Aquí se guardan los mensajes de error o reparos de SUNAT.', null=True, verbose_name='Observaciones de SUNAT'),
        ),
        migrations.AddField(
            model_name='venta',
            name='qr_code_data',
            field=models.TextField(blank=True, null=True, verbose_name='Datos para QR (Yape/Plin)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='vuelto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vuelto Entregado'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad Vendida'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario de Venta'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='stock_producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.stockproducto', verbose_name='Lote de Stock Afectado'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='subtotal_linea',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal de la Línea'),
        ),
        migrations.AlterField(
            model_name='detalleventa',
            name='unidad_venta',
            field=models.CharField(help_text='Unidad en la que se vendió el producto.', max_length=20, verbose_name='Unidad de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Cliente Asociado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado_facturacion_electronica',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado'), ('N/A', 'No Aplica')], default='N/A', max_length=20, verbose_name='Estado FE'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta (Crédito/Débito)'), ('YAPE', 'Yape / Plin'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('OTRO', 'Otro')], max_length=50, verbose_name='Método de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='numero_comprobante',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Comprobante'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_comprobante',
            field=models.CharField(choices=[('TICKET', 'Ticket de Venta'), ('BOLETA', 'Boleta de Venta'), ('FACTURA', 'Factura Electrónica')], max_length=20, verbose_name='Tipo de Comprobante'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='uuid_comprobante_fe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='UUID Comprobante FE'),
        ),
    ]
