# Generated by Django 4.2.23 on 2025-07-12 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_farmacia_activo'),
        ('ventas', '0002_remove_detalleventa_descuento_linea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de Apertura')),
                ('monto_final_sistema', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final (Según Sistema)')),
                ('monto_final_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Final (Contado Real)')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diferencia de Caja')),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Apertura')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Cierre')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10, verbose_name='Estado de la Sesión')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones de Cierre')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario de Caja')),
            ],
            options={
                'verbose_name': 'Sesión de Caja',
                'verbose_name_plural': 'Sesiones de Caja',
                'ordering': ['-fecha_apertura'],
            },
        ),
    ]
