# Generated by Django 4.2.23 on 2025-07-16 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_sesioncaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='sesion_caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ventas.sesioncaja', verbose_name='Sesión de Caja'),
        ),
    ]
