# Generated by Django 4.2.23 on 2026-06-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_venta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.PositiveIntegerField(verbose_name='Cantidad Vendida'),
        ),
    ]
