# Generated by Django 4.2.23 on 2026-05-02 23:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_farmacia_activo'),
        ('ventas', '0005_alter_venta_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura Electrónica'), ('03', 'Boleta de Venta Electrónica'), ('07', 'Nota de Crédito Electrónica'), ('08', 'Nota de Débito Electrónica')], max_length=2)),
                ('serie', models.CharField(max_length=4)),
                ('numero', models.PositiveIntegerField()),
                ('codigo_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('ambiente', models.CharField(choices=[('BETA', 'Beta / Pruebas'), ('PRODUCCION', 'Producción')], default='BETA', max_length=20)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente de Envío'), ('GENERADO', 'XML Generado'), ('FIRMADO', 'XML Firmado'), ('ENVIADO', 'Enviado a SUNAT/OSE'), ('ACEPTADO', 'Aceptado'), ('ACEPTADO_OBSERVADO', 'Aceptado con Observaciones'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=30)),
                ('moneda', models.CharField(choices=[('PEN', 'Soles'), ('USD', 'Dólares')], default='PEN', max_length=3)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('ruc_emisor', models.CharField(max_length=11)),
                ('razon_social_emisor', models.CharField(max_length=255)),
                ('nombre_comercial_emisor', models.CharField(blank=True, max_length=255)),
                ('direccion_emisor', models.CharField(blank=True, max_length=255)),
                ('ubigeo_emisor', models.CharField(blank=True, max_length=6)),
                ('tipo_documento_cliente', models.CharField(blank=True, max_length=2)),
                ('numero_documento_cliente', models.CharField(blank=True, max_length=20)),
                ('nombre_cliente', models.CharField(blank=True, max_length=255)),
                ('direccion_cliente', models.CharField(blank=True, max_length=255)),
                ('email_cliente', models.EmailField(blank=True, max_length=254)),
                ('total_gravado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_exonerado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_inafecto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_importe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('xml_nombre', models.CharField(blank=True, max_length=255)),
                ('xml_firmado', models.TextField(blank=True)),
                ('zip_base64', models.TextField(blank=True)),
                ('cdr_base64', models.TextField(blank=True)),
                ('sunat_ticket', models.CharField(blank=True, max_length=100)),
                ('sunat_codigo_respuesta', models.CharField(blank=True, max_length=20)),
                ('sunat_descripcion', models.TextField(blank=True)),
                ('sunat_notas', models.TextField(blank=True)),
                ('intentos_envio', models.PositiveIntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Comprobante Electrónico',
                'verbose_name_plural': 'Comprobantes Electrónicos',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='SerieComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('01', 'Factura Electrónica'), ('03', 'Boleta de Venta Electrónica'), ('07', 'Nota de Crédito Electrónica'), ('08', 'Nota de Débito Electrónica')], max_length=2)),
                ('serie', models.CharField(max_length=4)),
                ('correlativo_actual', models.PositiveIntegerField(default=0)),
                ('ambiente', models.CharField(choices=[('BETA', 'Beta / Pruebas'), ('PRODUCCION', 'Producción')], default='BETA', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_comprobantes', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Serie de Comprobante',
                'verbose_name_plural': 'Series de Comprobantes',
                'ordering': ['sucursal', 'tipo_comprobante', 'serie'],
                'unique_together': {('sucursal', 'tipo_comprobante', 'serie', 'ambiente')},
            },
        ),
        migrations.CreateModel(
            name='ResumenDiarioBoletas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resumen', models.DateField()),
                ('correlativo', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('ticket_sunat', models.CharField(blank=True, max_length=100)),
                ('xml_firmado', models.TextField(blank=True)),
                ('zip_base64', models.TextField(blank=True)),
                ('cdr_base64', models.TextField(blank=True)),
                ('sunat_codigo_respuesta', models.CharField(blank=True, max_length=20)),
                ('sunat_descripcion', models.TextField(blank=True)),
                ('ultimo_error', models.TextField(blank=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumenes_boletas', to='core.sucursal')),
            ],
            options={
                'verbose_name': 'Resumen Diario de Boletas',
                'verbose_name_plural': 'Resúmenes Diarios de Boletas',
                'ordering': ['-fecha_resumen', '-correlativo'],
                'unique_together': {('sucursal', 'fecha_resumen', 'correlativo')},
            },
        ),
        migrations.CreateModel(
            name='EventoComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=30)),
                ('estado_nuevo', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('respuesta_sunat', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='facturacion.comprobanteelectronico')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Comprobante Electrónico',
                'verbose_name_plural': 'Eventos de Comprobantes Electrónicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ComprobanteElectronicoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_codigo', models.CharField(blank=True, max_length=50)),
                ('producto_nombre', models.CharField(max_length=255)),
                ('unidad_medida', models.CharField(default='NIU', max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_unitario', models.DecimalField(decimal_places=6, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=6, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=12)),
                ('igv', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('codigo_tipo_afectacion_igv', models.CharField(default='10', max_length=2)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.comprobanteelectronico')),
                ('detalle_venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalle_facturacion', to='ventas.detalleventa')),
            ],
            options={
                'verbose_name': 'Detalle de Comprobante Electrónico',
                'verbose_name_plural': 'Detalles de Comprobante Electrónico',
            },
        ),
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='serie_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='facturacion.seriecomprobante'),
        ),
        migrations.AddField(
            model_name='comprobanteelectronico',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante_electronico', to='ventas.venta'),
        ),
        migrations.CreateModel(
            name='ResumenDiarioBoletaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_item', models.CharField(choices=[('1', 'Adicionar'), ('2', 'Modificar'), ('3', 'Anulado')], default='1', max_length=1)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resumenes_diarios', to='facturacion.comprobanteelectronico')),
                ('resumen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.resumendiarioboletas')),
            ],
            options={
                'verbose_name': 'Detalle de Resumen Diario',
                'verbose_name_plural': 'Detalles de Resumen Diario',
                'unique_together': {('resumen', 'comprobante')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='comprobanteelectronico',
            unique_together={('tipo_comprobante', 'serie', 'numero', 'ambiente')},
        ),
    ]
