# Generated by Django 4.2.23 on 2026-05-05 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_configuracionfacturacionelectronica_certificado_pem_and_more'),
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobanteelectronico',
            name='serie_comprobante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='core.seriecomprobante'),
        ),
        migrations.DeleteModel(
            name='SerieComprobante',
        ),
    ]
