# Generated by Django 4.2.23 on 2025-06-17 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("DNI", "Documento Nacional de Identidad"),
                            ("RUC", "Registro Único de Contribuyentes"),
                            ("PASAPORTE", "Pasaporte"),
                            ("CE", "Carnet de Extranjería"),
                            ("OTRO", "Otro"),
                        ],
                        default="DNI",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        help_text="Número de identificación del cliente (DNI, RUC, etc.).",
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Documento",
                    ),
                ),
                ("nombres", models.CharField(max_length=100, verbose_name="Nombres")),
                (
                    "apellidos",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Apellidos"
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=255, verbose_name="Email"),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "farmacia",
                    models.ForeignKey(
                        blank=True,
                        help_text="Farmacia principal a la que este cliente está asociado (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.farmacia",
                        verbose_name="Farmacia Principal del Cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["apellidos", "nombres"],
            },
        ),
    ]
