# Generated by Django 4.2.23 on 2025-06-17 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventario", "0001_initial"),
        ("proveedores", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CotizacionProveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_cotizacion",
                    models.DateField(verbose_name="Fecha de Cotización"),
                ),
                (
                    "fecha_validez",
                    models.DateField(
                        blank=True,
                        help_text="Fecha hasta la cual la cotización es válida.",
                        null=True,
                        verbose_name="Fecha de Validez",
                    ),
                ),
                (
                    "numero_cotizacion",
                    models.CharField(
                        help_text="Número de referencia de la cotización del proveedor.",
                        max_length=100,
                        unique=True,
                        verbose_name="Número de Cotización",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total_cotizacion",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total Cotización",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Revisión"),
                            (
                                "ACEPTADA",
                                "Aceptada (puede generar una Orden de Compra)",
                            ),
                            ("RECHAZADA", "Rechazada"),
                            ("EXPIRADA", "Expirada (fuera de fecha de validez)"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Cotización",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, verbose_name="Observaciones Adicionales"
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cotización Creada Por",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cotización de Proveedor",
                "verbose_name_plural": "Cotizaciones de Proveedores",
                "ordering": ["-fecha_cotizacion", "proveedor__nombre_comercial"],
            },
        ),
        migrations.CreateModel(
            name="OrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_orden",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de la Orden de Compra"
                    ),
                ),
                (
                    "fecha_entrega_estimada",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Entrega Estimada"
                    ),
                ),
                (
                    "numero_orden",
                    models.CharField(
                        help_text="Número único de referencia de la orden de compra.",
                        max_length=100,
                        unique=True,
                        verbose_name="Número de Orden de Compra",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total_orden",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total Orden",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Envío"),
                            ("ENVIADA", "Enviada al Proveedor"),
                            ("RECIBIDA_PARCIAL", "Recibida Parcialmente"),
                            ("RECIBIDA_TOTAL", "Recibida Totalmente"),
                            ("CANCELADA", "Cancelada"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Orden",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "cotizacion_base",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cotización de la que se generó esta Orden de Compra (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compras.cotizacionproveedor",
                        verbose_name="Cotización de Base",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Orden Creada Por",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "sucursal_destino",
                    models.ForeignKey(
                        help_text="Sucursal donde se espera recibir los productos de esta orden.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.sucursal",
                        verbose_name="Sucursal de Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
                "ordering": ["-fecha_orden", "numero_orden"],
            },
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_recepcion",
                    models.DateField(
                        auto_now_add=True, verbose_name="Fecha de Recepción"
                    ),
                ),
                (
                    "numero_factura_proveedor",
                    models.CharField(
                        help_text="Número del documento fiscal emitido por el proveedor.",
                        max_length=100,
                        unique=True,
                        verbose_name="Número de Factura/Guía de Remisión del Proveedor",
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Subtotal",
                    ),
                ),
                (
                    "impuestos",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Impuestos",
                    ),
                ),
                (
                    "total_compra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Total de la Compra",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente de Procesamiento"),
                            ("PROCESADA", "Procesada y Stock Actualizado"),
                            ("ANULADA", "Anulada (Stock no afectado o revertido)"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                        verbose_name="Estado de la Compra",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "orden_compra_asociada",
                    models.ForeignKey(
                        blank=True,
                        help_text="Orden de Compra a la que corresponde esta recepción (opcional).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="compras.ordencompra",
                        verbose_name="Orden de Compra Asociada",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="proveedores.proveedor",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        help_text="Usuario que registró la recepción de esta compra.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado Por",
                    ),
                ),
                (
                    "sucursal_destino",
                    models.ForeignKey(
                        help_text="Sucursal donde se recibirán los productos.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.sucursal",
                        verbose_name="Sucursal de Destino",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra (Recepción)",
                "verbose_name_plural": "Compras (Recepciones)",
                "ordering": ["-fecha_recepcion", "numero_factura_proveedor"],
            },
        ),
        migrations.CreateModel(
            name="DetalleOrdenCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_solicitada",
                    models.IntegerField(verbose_name="Cantidad Solicitada"),
                ),
                (
                    "cantidad_recibida",
                    models.IntegerField(
                        default=0,
                        help_text="Cantidad de este producto ya recibida para esta orden.",
                        verbose_name="Cantidad Recibida",
                    ),
                ),
                (
                    "precio_unitario_oc",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio Unitario Ordenado",
                    ),
                ),
                (
                    "subtotal_linea",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Subtotal de Línea",
                    ),
                ),
                (
                    "orden_compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.ordencompra",
                        verbose_name="Orden de Compra Asociada",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                        verbose_name="Producto Solicitado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Orden de Compra",
                "verbose_name_plural": "Detalles de Órdenes de Compra",
                "unique_together": {("orden_compra", "producto")},
            },
        ),
        migrations.CreateModel(
            name="DetalleCotizacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField(verbose_name="Cantidad Cotizada")),
                (
                    "precio_unitario_cotizado",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio Unitario Cotizado",
                    ),
                ),
                (
                    "subtotal_linea",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Subtotal de Línea",
                    ),
                ),
                (
                    "cotizacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.cotizacionproveedor",
                        verbose_name="Cotización Asociada",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                        verbose_name="Producto Cotizado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Cotización",
                "verbose_name_plural": "Detalles de Cotización",
                "unique_together": {("cotizacion", "producto")},
            },
        ),
        migrations.CreateModel(
            name="DetalleCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_recibida",
                    models.IntegerField(verbose_name="Cantidad Recibida"),
                ),
                (
                    "precio_unitario_compra",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Precio Unitario de Compra",
                    ),
                ),
                (
                    "lote",
                    models.CharField(max_length=50, verbose_name="Número de Lote"),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de Vencimiento del Lote"),
                ),
                (
                    "subtotal_linea",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Subtotal de Línea",
                    ),
                ),
                (
                    "compra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="compras.compra",
                        verbose_name="Compra Asociada",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario.producto",
                        verbose_name="Producto Recibido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Compra",
                "verbose_name_plural": "Detalles de Compras",
                "unique_together": {("compra", "producto", "lote")},
            },
        ),
    ]
