# Generated by Django 4.2.23 on 2025-07-09 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compras", "0002_alter_compra_numero_factura_proveedor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detallecompra",
            name="cantidad_recibida",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Cantidad Recibida"
            ),
        ),
        migrations.AlterField(
            model_name="detallecompra",
            name="subtotal_linea",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                editable=False,
                max_digits=12,
                verbose_name="Subtotal de Línea",
            ),
        ),
    ]
