# Generated by Django 4.2.23 on 2025-07-10 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('compras', '0004_detallecompra_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='impuestos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Impuestos'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='orden_compra_asociada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.ordencompra', verbose_name='Orden de Compra Asociada'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Registrado Por'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='Sucursal de Destino'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='total_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Total de la Compra'),
        ),
    ]
