# Generated by Django 4.2.23 on 2025-06-17 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_comercial",
                    models.CharField(
                        max_length=200, verbose_name="Nombre Comercial del Proveedor"
                    ),
                ),
                (
                    "razon_social",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Razón Social"
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("RUC", "Registro Único de Contribuyentes"),
                            ("NIT", "Número de Identificación Tributaria"),
                            ("TAX_ID", "Tax ID / EIN"),
                            ("CIF", "Certificado de Identificación Fiscal"),
                            ("OTRO", "Otro"),
                        ],
                        default="RUC",
                        max_length=20,
                        verbose_name="Tipo de Documento Fiscal",
                    ),
                ),
                (
                    "numero_documento",
                    models.CharField(
                        help_text="Número de identificación fiscal o tributaria del proveedor.",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Documento Fiscal",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Dirección Principal"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono Principal"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, verbose_name="Email de Contacto"
                    ),
                ),
                (
                    "sitio_web",
                    models.URLField(
                        blank=True, max_length=255, verbose_name="Sitio Web"
                    ),
                ),
                (
                    "persona_contacto",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Persona de Contacto"
                    ),
                ),
                (
                    "telefono_contacto",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        verbose_name="Teléfono de Contacto Adicional",
                    ),
                ),
                (
                    "condiciones_pago",
                    models.TextField(
                        blank=True, verbose_name="Condiciones de Pago Estandar"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el proveedor está activo y puede usarse para compras.",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "fecha_registro",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
                "ordering": ["nombre_comercial"],
            },
        ),
    ]
